## NLP Practical Session 1: Python Setup, Conda Environments, and PyTorch Basics

    FAU Erlangen — NLP Course
    Instructor: Gozde Gul Sahin


### Part 0: Setup Instructions (Before Jupyter)

Download Miniconda (if not installed) -> Visit: https://docs.conda.io/en/latest/miniconda.html

Start your terminal on your PC and run the followings:
1. Create a new environment for NLP course -> `conda create -n nlp_course python=3.10`
2. Activate environment -> `conda activate nlp_course`
3. Install Jupyter, NumPy and PyTorch
    - `conda install jupyter numpy`
    - conda install pytorch
4. Launch Jupyter Lab/Notebook -> `jupyter notebook`


## Part 1: Python Basics (Inside Jupyter)

#### First Python commands

In [1]:
print("Hello, NLP class!")

Hello, NLP class!


In [2]:
# Simple arithmetic
addition = 5 + 3
multiplication = 4 * 7
print(f"5+3={addition}, 4*7={multiplication}")

5+3=8, 4*7=28


#### Variables and data types

In [3]:
# String
course_name = "Natural Language Processing"

# Integer
year = 2026

# Float
pi_approx = 3.14159

# Boolean
is_fun = True

print(f"Course: {course_name}, Year: {year}, Pi: {pi_approx}, Fun? {is_fun}")
print(f"Type of year: {type(year)}")

Course: Natural Language Processing, Year: 2026, Pi: 3.14159, Fun? True
Type of year: <class 'int'>


#### Lists and indexing

In [4]:
# List of words
tokens = ["Hello", "world", "NLP", "is", "awesome"]

# Indexing (0-based)
first_word = tokens[0]
last_word = tokens[-1]

print(f"First token: {first_word}")
print(f"Last token: {last_word}")

# Slicing
first_two = tokens[:2]
print(f"First two: {first_two}")

# List methods
tokens.append("!")
print(f"After append: {tokens}")

First token: Hello
Last token: awesome
First two: ['Hello', 'world']
After append: ['Hello', 'world', 'NLP', 'is', 'awesome', '!']


#### Dictionaries (this is important especially for NLP features)

In [5]:
# Word to index mapping
word_to_idx = {
    "cat": 0,
    "dog": 1,
    "mouse": 2
}

print(word_to_idx["dog"])

# Adding a new word
word_to_idx["bird"] = 3
print(word_to_idx)

1
{'cat': 0, 'dog': 1, 'mouse': 2, 'bird': 3}


#### Loops and conditionals

In [6]:
# Loop through tokens
for token in tokens:
    if len(token) > 3:
        print(f"Long word: {token}")
    else:
        print(f"Short word: {token}")

# List comprehension (very Pythonic)
word_lengths = [len(w) for w in tokens]
print(f"Word lengths: {word_lengths}")

Long word: Hello
Long word: world
Short word: NLP
Short word: is
Long word: awesome
Short word: !
Word lengths: [5, 5, 3, 2, 7, 1]


#### Functions

In [7]:
def simple_tokenize(text):
    """Split text into words by spaces."""
    return text.split()

sample_text = "This is a simple sentence."
tokens = simple_tokenize(sample_text)
print(tokens)

['This', 'is', 'a', 'simple', 'sentence.']


## Part 2: NumPy Basics (Numerical Computing)

#### Import NumPy and check version

In [8]:
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.4.3


#### What is NumPy?

<img src="what_is_numpy.png" width="900">


#### Creating NumPy arrays

You may think of them as a list in python.

In [9]:
# From a list
arr_from_list = np.array([1, 2, 3, 4, 5])
print(f"Array: {arr_from_list}")
print(f"Shape: {arr_from_list.shape}")
print(f"Data type: {arr_from_list.dtype}")

# Special arrays
zeros = np.zeros((3, 4))  # 3 rows, 4 columns
ones = np.ones((2, 3))
identity = np.eye(4)  # Identity matrix
random_arr = np.random.rand(2, 3)  # Uniform distribution [0,1)

print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nIdentity matrix:\n", identity)
print("\nRandom array:\n", random_arr)

# arange and linspace
range_arr = np.arange(0, 10, 2)  # start, stop, step
linspace_arr = np.linspace(0, 1, 5)  # start, stop, number of points

print(f"\narange: {range_arr}")
print(f"linspace: {linspace_arr}")

Array: [1 2 3 4 5]
Shape: (5,)
Data type: int64

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random array:
 [[0.0295362  0.08551117 0.51544955]
 [0.21109725 0.40772319 0.96915603]]

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


<img src="numpy_arrays.png" width="900">

#### Array operations (element-wise)

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
print(f"a + b = {a + b}")
print(f"a * b = {a * b}")  # NThis is not matrix multiplication!
print(f"a ** 2 = {a ** 2}") # Taking square of each element in array "a"

# Universal functions (ufuncs)
print(f"sqrt(a) = {np.sqrt(a)}")
print(f"exp(a) = {np.exp(a)}")
print(f"mean(a) = {np.mean(a)}")
print(f"sum(a) = {np.sum(a)}")

a + b = [5 7 9]
a * b = [ 4 10 18]
a ** 2 = [1 4 9]
sqrt(a) = [1.         1.41421356 1.73205081]
exp(a) = [ 2.71828183  7.3890561  20.08553692]
mean(a) = 2.0
sum(a) = 6


#### Matrix operations

In [13]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_product = np.dot(A, B)  # or A @ B
print("Matrix A:\n", A, "\n")
print("Matrix B:\n", B, "\n")
print("A @ B:\n", dot_product, "\n")

# Transpose
print("Transpose of A:\n", A.T)

Matrix A:
 [[1 2]
 [3 4]] 

Matrix B:
 [[5 6]
 [7 8]] 

A @ B:
 [[19 22]
 [43 50]] 

Transpose of A:
 [[1 3]
 [2 4]]


#### Indexing and slicing (similar to Python lists)

In [14]:
# 2D array
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Original matrix:\n", matrix)

# Slicing
print("\nFirst two rows:\n", matrix[:2])
print("Last two columns:\n", matrix[:, -2:])
print("Element at row 1, col 2:", matrix[1, 2])

# Boolean indexing (very powerful)
mask = matrix > 5
print("\nMask (matrix > 5):\n", mask)
print("Values > 5:", matrix[mask])

Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First two rows:
 [[1 2 3 4]
 [5 6 7 8]]
Last two columns:
 [[ 3  4]
 [ 7  8]
 [11 12]]
Element at row 1, col 2: 7

Mask (matrix > 5):
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
Values > 5: [ 6  7  8  9 10 11 12]


#### Reshaping and aggregation

In [15]:
# Create a 1D array
data = np.arange(12)
print(f"Original: {data}")

# Reshape to 3x4
reshaped = data.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped)

# Flatten back
flattened = reshaped.flatten()
print(f"Flattened: {flattened}")

# Aggregation along axes
print(f"\nSum of all elements: {reshaped.sum()}")
print(f"Sum along rows (axis=0): {reshaped.sum(axis=0)}")  # Column sums
print(f"Sum along columns (axis=1): {reshaped.sum(axis=1)}")  # Row sums
print(f"Max value: {reshaped.max()}")
print(f"Index of max value: {reshaped.argmax()}")

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Sum of all elements: 66
Sum along rows (axis=0): [12 15 18 21]
Sum along columns (axis=1): [ 6 22 38]
Max value: 11
Index of max value: 11


#### Bonus: NumPy for NLP - Bag of words example

BUNU TEKRAR KONTROL EDECEĞİM

In [16]:
# Create a simple vocabulary
corpus = [
    "the cat sat on the mat",
    "the dog sat on the log",
    "cats and dogs are pets"
]

# Build vocabulary
vocab = set()
for sentence in corpus:
    for word in sentence.split():
        vocab.add(word)

vocab = sorted(vocab)
word_to_idx = {word: i for i, word in enumerate(vocab)}
print(f"Vocabulary size: {len(vocab)}")
print(f"Vocabulary: {vocab}\n")

# Create bag-of-words vectors
def create_bow(sentence, vocab, word_to_idx):
    bow = np.zeros(len(vocab))
    for word in sentence.split():
        if word in word_to_idx:
            bow[word_to_idx[word]] += 1
    return bow

# Create BoW for first sentence
sentence1 = corpus[0]
bow_vector = create_bow(sentence1, vocab, word_to_idx)

print(f"Sentence: '{sentence1}'")
print(f"BoW vector: {bow_vector}")
print(f"Vector shape: {bow_vector.shape}")

# Create document-term matrix
dt_matrix = np.array([create_bow(sent, vocab, word_to_idx) for sent in corpus])
print(f"\nDocument-Term Matrix shape: {dt_matrix.shape}")
print("Document-Term Matrix:\n", dt_matrix)

Vocabulary size: 12
Vocabulary: ['and', 'are', 'cat', 'cats', 'dog', 'dogs', 'log', 'mat', 'on', 'pets', 'sat', 'the']

Sentence: 'the cat sat on the mat'
BoW vector: [0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 2.]
Vector shape: (12,)

Document-Term Matrix shape: (3, 12)
Document-Term Matrix:
 [[0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 2.]
 [0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 2.]
 [1. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0.]]


## Part 3: PyTorch Basics (Transition from NumPy)

<img src="what_is_pytorch.jpg" width="900">

#### Import PyTorch and compare with NumPy

In [19]:
import torch
print(f"PyTorch version: {torch.__version__}")
print(f"Is CUDA available? {torch.cuda.is_available()}") # for linux users
print(f"Is mps available? {torch.backends.mps.is_available()}") # for MacOS users

# NumPy array
np_array = np.array([[1, 2], [3, 4]])
print("NumPy array:\n", np_array)

# Convert to PyTorch tensor
tensor_from_numpy = torch.from_numpy(np_array)
print("\nPyTorch tensor from NumPy:\n", tensor_from_numpy)

# Convert back to NumPy
back_to_numpy = tensor_from_numpy.numpy()
print("\nBack to NumPy:\n", back_to_numpy)

PyTorch version: 2.11.0
Is CUDA available? False
Is mps available? True
NumPy array:
 [[1 2]
 [3 4]]

PyTorch tensor from NumPy:
 tensor([[1, 2],
        [3, 4]])

Back to NumPy:
 [[1 2]
 [3 4]]


#### Creating tensors (similar to NumPy)

In [20]:
# From a list
tensor_from_list = torch.tensor([1, 2, 3, 4, 5])
print(f"Tensor: {tensor_from_list}")
print(f"Shape: {tensor_from_list.shape}")
print(f"Data type: {tensor_from_list.dtype}")

# Similar to NumPy functions
zeros = torch.zeros(3, 4)
ones = torch.ones(2, 3)
identity = torch.eye(4)
random_tensor = torch.rand(2, 3)  # Uniform [0,1)

print("\nZeros:\n", zeros)
print("\nRandom:\n", random_tensor)

# arange equivalent
range_tensor = torch.arange(0, 10, 2)
print(f"\ntorch.arange: {range_tensor}")

Tensor: tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])
Data type: torch.int64

Zeros:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Random:
 tensor([[0.7770, 0.8336, 0.6834],
        [0.8775, 0.4953, 0.2736]])

torch.arange: tensor([0, 2, 4, 6, 8])


#### Tensor operations (NumPy-like but with GPU support)

In [21]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

# Element-wise operations (same as NumPy)
print(f"a + b = {a + b}")
print(f"a * b = {a * b}")
print(f"a ** 2 = {a ** 2}")

# Matrix multiplication
A = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
B = torch.tensor([[5.0, 6.0], [7.0, 8.0]])
print("\nA @ B:\n", torch.mm(A, B))  # or A @ B

# Aggregation
print(f"\nMean of a: {a.mean()}")
print(f"Sum of a: {a.sum()}")

a + b = tensor([5., 7., 9.])
a * b = tensor([ 4., 10., 18.])
a ** 2 = tensor([1., 4., 9.])

A @ B:
 tensor([[19., 22.],
        [43., 50.]])

Mean of a: 2.0
Sum of a: 6.0


#### Reshaping and indexing (identical to NumPy)

In [ ]:
# Reshape
data = torch.arange(12)
reshaped = data.view(3, 4)  # .reshape() also works
print("Reshaped to 3x4:\n", reshaped)

# Indexing and slicing
matrix = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("\nFirst two rows:\n", matrix[:2])
print("Last two columns:\n", matrix[:, -2:])
print("Element at (1,2):", matrix[1, 2])

#### Gradients and autograd (NumPy doesn't have this!)

#### Differantiation Operations with PyTorch
<img src="auto_diff.png" width="900">

In [23]:
# Create tensor with requires_grad=True to track computations
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x + 1  # y = x^2 + 3x + 1

# Compute gradient dy/dx
y.backward()

print(f"x = {x}")
print(f"y = {y}")
print(f"dy/dx at x=2: {x.grad}")  # Should be 2*2 + 3 = 7

x = 2.0
y = 11.0
dy/dx at x=2: 7.0


#### Moving tensors to GPU (if available)

In [25]:
# Check if GPU is available
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"GPU available: {torch.cuda.get_device_name(0)}")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
    print(f"GPU available: {torch.backends.mps.is_available()}")
else:
    device = torch.device("cpu")
    print("GPU not available, using CPU")

# Create tensor and move to device
tensor_cpu = torch.tensor([1.0, 2.0, 3.0])
tensor_gpu = tensor_cpu.to(device)

print(f"CPU tensor device: {tensor_cpu.device}")
print(f"GPU tensor device: {tensor_gpu.device}")

# Move back to CPU if needed
tensor_back_to_cpu = tensor_gpu.cpu()

GPU available: True
CPU tensor device: cpu
GPU tensor device: mps:0


#### Simple linear regression example and PyTorch Training Loop

In [26]:
# Generate synthetic data
torch.manual_seed(42)
np.random.seed(42)

X = torch.linspace(0, 10, 100).reshape(-1, 1)
true_w = 2.0
true_b = 1.0
y = true_w * X + true_b + 0.5 * torch.randn(X.shape)

# Define a simple linear model
class LinearModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

model = LinearModel()

# Loss and optimizer
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Training loop
print("Training PyTorch model...")
for epoch in range(100):
    y_pred = model(X)
    loss = loss_fn(y_pred, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 20 == 0:
        print(f"Epoch {epoch+1}: Loss = {loss.item():.4f}")

# Learned parameters
learned_w = model.linear.weight.item()
learned_b = model.linear.bias.item()
print(f"\nTrue: w={true_w}, b={true_b}")
print(f"Learned: w={learned_w:.4f}, b={learned_b:.4f}")

Training PyTorch model...
Epoch 20: Loss = 0.7862
Epoch 40: Loss = 0.6877
Epoch 60: Loss = 0.6071
Epoch 80: Loss = 0.5409
Epoch 100: Loss = 0.4867

True: w=2.0, b=1.0
Learned: w=2.1444, b=0.0650


#### Working with text in PyTorch (NLP teaser)

In [27]:
# Simple vocabulary
words = ["hello", "world", "nlp", "pytorch", "fun"]
word_to_ix = {word: i for i, word in enumerate(words)}
ix_to_word = {i: word for word, i in word_to_ix.items()}

# Convert sentence to indices
sentence = ["hello", "nlp", "fun"]
indices = [word_to_ix[w] for w in sentence]
print(f"Sentence indices: {indices}")

# One-hot encoding (simplified)
def one_hot(indices, vocab_size):
    return torch.eye(vocab_size)[indices]

one_hot_vectors = one_hot(indices, len(words))
print(f"One-hot vectors:\n{one_hot_vectors}")

# Embedding layer (learnable representations)
embedding = torch.nn.Embedding(num_embeddings=len(words), embedding_dim=5)
embedded = embedding(torch.tensor(indices))
print(f"\nEmbedded shape: {embedded.shape}")
print(f"Embedded vectors:\n{embedded}")

Sentence indices: [0, 2, 4]
One-hot vectors:
tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.]])

Embedded shape: torch.Size([3, 5])
Embedded vectors:
tensor([[-0.3891,  0.5279,  1.0311, -0.7048,  1.0131],
        [-0.9727,  0.9585,  1.6192,  1.4506,  0.2695],
        [-0.4657,  1.6048, -2.4801, -0.4175, -1.1955]],
       grad_fn=<EmbeddingBackward0>)


## Part 4: Quick Exercises for Students

#### Exercise 1 - NumPy word frequency

In [ ]:
# TODO: Create a document-term matrix using NumPy
documents = [
    "nlp is fun",
    "pytorch is powerful",
    "nlp and pytorch are great"
]

# Your code here:
# 1. Build vocabulary
# 2. Create BoW vectors using NumPy
# 3. Compute document-term matrix

# Solution structure:
vocab = sorted(set(" ".join(documents).split()))
word_to_idx = {w:i for i,w in enumerate(vocab)}
dt_matrix = np.zeros((len(documents), len(vocab)))

for i, doc in enumerate(documents):
    for word in doc.split():
        dt_matrix[i, word_to_idx[word]] += 1

print("Vocabulary:", vocab)
print("Document-Term Matrix:\n", dt_matrix)

#### Exercise 2 - Tensor manipulation (NumPy vs PyTorch)

In [ ]:
# TODO: Perform the same operations in NumPy and PyTorch
# 1. Create a 4x4 random matrix
# 2. Compute its transpose
# 3. Compute the sum of each row
# 4. Compute the matrix product with its transpose

# NumPy version
print("NumPy version:")
np_mat = np.random.rand(4, 4)
print("Matrix:\n", np_mat)
print("Transpose:\n", np_mat.T)
print("Row sums:", np_mat.sum(axis=1))
print("Product with transpose:\n", np_mat @ np_mat.T)

# PyTorch version
print("\nPyTorch version:")
torch_mat = torch.rand(4, 4)
print("Matrix:\n", torch_mat)
print("Transpose:\n", torch_mat.T)
print("Row sums:", torch_mat.sum(dim=1))
print("Product with transpose:\n", torch_mat @ torch_mat.T)

#### Exercise 3 - Simple text classifier stub

In [ ]:
# TODO: Create a tiny neural network for binary sentiment classification
# Input: 10-dimensional word embedding, Output: positive/negative (2 classes)

class TinySentimentClassifier(torch.nn.Module):
    def __init__(self, embedding_dim=10, hidden_dim=5, output_dim=2):
        super().__init__()
        # Define layers here
        self.fc1 = torch.nn.Linear(embedding_dim, hidden_dim)
        self.fc2 = torch.nn.Linear(hidden_dim, output_dim)
        self.relu = torch.nn.ReLU()

    def forward(self, x):
        # Define forward pass
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Test with random input
model = TinySentimentClassifier()
sample_input = torch.rand(3, 10)  # batch of 3 samples, 10-dim each
output = model(sample_input)
print(f"Output shape: {output.shape}")  # Should be [3, 2]

#### Bonus Exercise - NumPy vs PyTorch performance

In [28]:
# Compare matrix multiplication speed (CPU only)
import time

size = 1000
np_a = np.random.rand(size, size)
np_b = np.random.rand(size, size)
torch_a = torch.tensor(np_a)
torch_b = torch.tensor(np_b)

# NumPy
start = time.time()
np_result = np_a @ np_b
np_time = time.time() - start

# PyTorch
start = time.time()
torch_result = torch_a @ torch_b
torch_time = time.time() - start

print(f"NumPy time: {np_time:.4f} seconds")
print(f"PyTorch time: {torch_time:.4f} seconds")
print(f"PyTorch is {np_time/torch_time:.2f}x faster")

NumPy time: 0.0305 seconds
PyTorch time: 0.0093 seconds
PyTorch is 3.28x faster
